[build]
  functions = "functions"
  publish = "public"

# 根路径 - 显示Web界面
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# 静态文件路由
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
