[build]
  functions = "functions"
  publish = "public"

# 重定向所有路径到函数
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

# 单独处理根路径
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# 静态文件路由
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
